sudo: false
node_js:
  - 6
  - 5
  - 4
  - .12
  - .10
language: node_js
script: PATH="$PATH:$HOME/bin" npm test
before_test:
  - git clone --recursive git://github.com/nvie/gitflow.git
  - cd gitflow
  - make install prefix=$HOME

